library(shiny)
shinyUI(fluidPage(

     plotOutput('plot'),
     
     hr(),
     
     fluidRow(
          column(4,
                 HTML("<h3><u>Sunk Costs & Offsets Realized</u></h3>"),
                 fluidRow(
                      column(6,
                             HTML("<h4><em><b>PolicySmart Classic</b></em></h4>"),
                             sliderInput(inputId = "AmyHoursIn",
                                         label = "AM Hours",
                                         min = 0, max = 3000, value = 1500, step = 10),
                             numericInput(inputId = "AmyRate",
                                          label = "AM Rate",
                                          min = 0, max = 500, value =250),
                             numericInput(inputId = "ShareholderBill",
                                          label = "SH Lump",
                                          min = 0, max = 100000, value = 44700),
                             HTML("<h4><em><b>Offsets Realized</b></em></h4>"),
                             numericInput(inputId = "Xpert",
                                          label = "Offset from X",
                                          min = 0, max = 100000, value = 70000)
                      ),
                      column(6,
                             HTML("<h4><em><b>Field Guide & Tech Costs</b></em></h4>"),
                             numericInput(inputId = "HighQ",
                                          label = "Startup Cost for HighQ Collaborate",
                                          min = 0, max = 75000, value = 35000),
                             numericInput(inputId = "AttyGroup",
                                          label = "Atty Lump",
                                          min = 0, max = 200000, value = 145000),
                             HTML("<h4><em><b>Offsets Realized</b></em></h4>"),
                             numericInput(inputId = "AFLAC",
                                          label = "Client A Receivable",
                                          min = 0, max = 100000, value = 60000),
                             numericInput(inputId = "TriNet",
                                          label = "Client T Receivable",
                                          min = 0, max = 100000, value = 60000),
                             numericInput(inputId = "Amazon",
                                          label = "Client A2 receivable",
                                          min = 0, max = 100000, value = 25000),
                             numericInput(inputId = "HighQIn",
                                          label = "Current Subscriptions to HighQ Products",
                                          min = 0, max = 100000, value = 35000)
                      )
                 )
          ),
          column(4,
                 HTML("<h3><u>Projected Costs and Offsets</u></h3>"),
                 fluidRow(
                      column(6,
                             HTML("<h4><em><b>PolicySmart Classic Upkeep</b></em></h4>"),
                             sliderInput(inputId = "AmyProjectedHrs",
                                         label = "AM Projected Billable Hours",
                                         min = 0, max = 3000, value = 1260, step = 10),
                             numericInput(inputId = "AmyProjectedRate",
                                          label = "AM Bill Rate",
                                          min = 0, max = 500, value =250),
                             sliderInput(inputId = "supportHrs",
                                         label = "Projected Billable Hours in Support",
                                         min = 0, max = 200, value = 108, step = 1),
                             numericInput(inputId = "supportRate",
                                          label = "Projected Bill Rate for Support",
                                          min = 0, max = 1000, value = 500),
                             HTML("<h4><em><b>Offsets Projected</b></em></h4>"),
                             numericInput(inputId = "XpertRevProj",
                                          label = "Client X Projected Total Revenue",
                                          min = 0, max = 100000, value = 82500),
                             numericInput(inputId = "templateUse",
                                          label = "Template Use Fees",
                                          min = 0, max = 100000, value = 72000)
                      ),
                      column(6,
                             HTML("<h4><em><b>Projected Field Guide & Tech Costs</b></em></h4>"),
                             sliderInput(inputId = "upkeepHours",
                                         label = "Total Projected Hours of Upkeep",
                                         min = 0, max = 2000, value = 1080, step = 10),
                             numericInput(inputId = "attyRate",
                                          label = "Projected Bill Rate",
                                          min = 0, max = 500, value = 250),
                             sliderInput(inputId = "prorataKM",
                                         label = "Prorated % of Total Cost Allocable",
                                         min = 0, max = 1, value = .25, step = .01),
                             numericInput(inputId = "HighQOutfees",
                                          label = "Projected Total Cost of HighQ Collaborate",
                                          min = 0, max = 120000, value = 90000),
                             sliderInput(inputId = "prorataHighQKM",
                                         label = "Prorated % of Total Cost of HighQ Collaborate Allocable",
                                         min = 0, max = 1, value = .20, step = .01)
                      )
                 )
                 
          ),
          column(4,
               HTML("<h3><u>Pricing Outcomes</u></h3>"),
               h6("Use the three generators below to produce worst, expected, and best case scenarios for the proposed price."),
               HTML("<h4><em><b>Pricing Option 1</b></em></h4>"),
               numericInput(inputId = "price1",
                            label = "Proposed Price 1",
                            min = 0, max = 25000, value = 20000),
               sliderInput(inputId = "numSubs1",
                           label = "Number of Subscriptions Anticipated at Price 1",
                           min = 0, max = 100, value = 20),
               
               HTML("<h4><em><b>Pricing Option 2</b></em></h4>"),
               numericInput(inputId = "price2",
                            label = "Proposed Price 2",
                            min = 0, max = 25000, value = 20000),
               sliderInput(inputId = "numSubs2",
                           label = "Number of Subscriptions Anticipated at Price 2",
                           min = 0, max = 100, value = 30),
               
               HTML("<h4><em><b>Pricing Option 3</b></em></h4>"),
               numericInput(inputId = "price3",
                            label = "Proposed Price 3",
                            min = 0, max = 25000, value = 20000),
               sliderInput(inputId = "numSubs3",
                           label = "Number of Subscriptions Anticipated at Price 3",
                           min = 0, max = 100, value = 40),
               
               HTML("<h4><em><b>Pricing Option 4</b></em></h4>"),
               numericInput(inputId = "price4",
                            label = "Proposed Price 4",
                            min = 0, max = 25000, value = 15000),
               sliderInput(inputId = "numSubs4",
                           label = "Number of Subscriptions Anticipated at Price 4",
                           min = 0, max = 100, value = 30),
               
               HTML("<h4><em><b>Pricing Option 5</b></em></h4>"),
               numericInput(inputId = "price5",
                            label = "Proposed Price 5",
                            min = 0, max = 25000, value = 15000),
               sliderInput(inputId = "numSubs5",
                           label = "Number of Subscriptions Anticipated at Price 5",
                           min = 0, max = 100, value = 40),
               
               HTML("<h4><em><b>Pricing Option 6</b></em></h4>"),
               numericInput(inputId = "price6",
                            label = "Proposed Price 6",
                            min = 0, max = 25000, value = 15000),
               sliderInput(inputId = "numSubs6",
                           label = "Number of Subscriptions Anticipated at Price 6",
                           min = 0, max = 100, value = 50)
          )
     ),
     hr(),
     HTML("<p><i>Developed 4/2015.</br>Michael S Lee</i></p>")
)
)
                              
               
